dist: trusty
language: cpp
sudo: false
compiler:
  - clang
  - gcc
env:
  global: CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY
addons:
  postgresql: '9.3'
  apt:
    sources:
      - llvm-toolchain-trusty-3.5
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-3.5
    - flex
    - g++-4.9
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - pkg-config
    - clang-format-5.0
    - pandoc
    - build-essential
    - rpm

cript: travis_wait 60 ./travis-build.sh
cache:
  directories:
  - "$HOME/.ccache"
  - ".libs"
notifications:
  email: false
  slack:
    secure: a8rcL4V8xMB9t10t/izM3lMUN7xoXGW29HB885WaeBH/37q8y3l/m6bnIcCDAQUmt1QsentoEGSL1w/eCroM8GSTNabF7czVBn1zhLOFJ4k33jxgoK1fPBjYTE0U/IXZLzXJvD/NDL/jZzTuA4Gd+4L2I6UThN8bEmHVz/Y1rSOvoelst87xdZ4aRnvEWoYDhtZdJW3IUvivRf4iLB79VGFjxSp+uJe/MNi5Pf2V/deOb+peXpMiaSqM/xdT5yVnp/EI8n0qYNaA8EHGNgM7OGP7IRd6uBPmCsOP1iJoY+Y3ZkfuGlFZiRETJukMkuhLjjS+nL6n/DLcN2452pVsxJz8nNoa/2sd3ouJygYmmqGJ8h/FNLrBP+7OlH/R4y5LL1e8l7U1MgVfvUqFriOykcBMlUFjgbCgDJMJ1UdaHorvZ+9YQtkthHdmG43Y3KkxKzMYPd7cbQZrBaVAozgV+ipLdkT2ssppqjV/JyY6vs+SIHA9x46Rr3NZdaN8eVInYOdKliTjsxXbhaa6sHOs8YEPEULtyPpPi62ZwraWKJ1X149uJn78Yd1r0+S4r39u0k7sQuZ+c09Ftci8R66Wqvwm32cj3USM2x2lSHhZctsDEnGdCJxrWX153wfeqpat0prYVGhD0mHobwEhP2ipajvh3TbwXkpeAASa5eeEJJE=


before_install:
  - export GEM_HOME=$HOME/.gem
  - export GEM_PATH=$HOME/.gem
  - rvm get stable --auto-dotfiles
  - rvm install 2.3.1
  - gem install --no-ri --no-rdoc fpm
  - fpm --version
  - fpm --help
  - export PATH=$(ruby -r rubygems -e 'puts Gem.dir'):$PATH
#  - fpm -s dir -t deb -C src --name digitalbits-core --version 0.1.0 --iteration 1 --depends debian_dependency1 --description "Digitalbits-core" .
#  - fpm -s dir -t rpm -C src --name digitalbits-core --version 0.1.0 --iteration 1 --depends  redhat_dependency1 --description "digitalbits-core" .
  
before_deploy: 
  - export PATH=$(ruby -r rubygems -e 'puts Gem.dir'):$PATH
  - pyenv global 2.7
  - pip install cloudsmith-cli
  - gem install --no-ri --no-rdoc fpm
  - fpm --version

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh 2>&1
  on:
    branch: OS-16