language: cpp
sudo: false

compiler:
- clang
- gcc

addons:
  postgresql: "9.3"
  apt:
    sources:
    - llvm-toolchain-trusty-3.5
    - llvm-toolchain-trusty-5.0
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-3.5
    - flex
    - g++-4.9
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - pkg-config
    - clang-format-5.0
    - pandoc

script: travis_wait 30 ./travis-build.sh

cache:
  directories:
  - $HOME/.ccache
  - .libs

notifications:
  email: false
before_deploy: 
  - pyenv global 2.7
  - pip install cloudsmith-cli
deploy:
  - provider: script
  - script: cloudsmith push rpm digitalbits/dbtest digitalbits-core.x86_64.rpm  
  - on: 
      branch: dev-deploy
