dist: trusty
language: cpp
sudo: false

compiler:
  - clang
  - gcc

addons:
  postgresql: "9.3"
  apt:
    sources:
    - llvm-toolchain-trusty-3.5
    - llvm-toolchain-trusty-5.0
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-3.5
    - flex
    - g++-4.9
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - pkg-config
    - clang-format-5.0
    - pandoc
    - build-essential
    - rpm

script: travis_wait 60 ./travis-build.sh

cache:
  directories:
    - $HOME/.ccache
    - .libs

notifications:
  email: false
  slack:
    secure: YV6WSA6tdswz7dvDw9f/8VF5Lb5E5dWNfnVYmPePqY/4guvCxtgLtK3ciqc/Z/+s6pnAgWCxNkL1TXcxkvQ13TZCnYLGz3gSpB0N1WF9hRoWPDVVlthUma7HwQYaWQcAXA5IkrfXfSN9PoJ4dtTWfFwSeBj4aIM5mzV/m6pOMXfOx1+7LxOXIonFrguHEr9zpU6SDmo7yYuk6bsCSNTqfFbYZtqApUip+PxhL0kRW2pLYjLVUOXxj+Pgt85uyZbcD7KmEjWzgITu/Emlg/Nwcy3QnPheeAg2mucI/8PvJ5UOCi1I7Pp8nSt8iJe5nXzkhlffKw06fM2IT2u4Ui31NY8ZK0zxXHfhR6Cdt5guRJe8/rXXa/7mALflErx1E5C2CMN+aXi3RmLmNJbHhg0ZjacI7WRuAJBZlPQ1MtqQEo/19BBjUk7MDRoG9e/vt9FROxHKMFaEUw9Qalclmpw0Mpgr8LGkqg8aNG1s6iq43qC8G7BPsIdEy2EG/t79dq+KKdeueOUHjkyHxTyiRHR23GvVHc7oX37+qjfw/EGwOR928XAYss6jxHbBYfxZwouYwQNtRlEEN6zlT0j/ApSANveMdjIgAOLj1+FLAKeuPw/blYko9XFZatBNiiVtlx0AqA4yBAwUnucIDgYyjMMK4B2ymxWJwvELwv9EJD8XaiY=

before_install:
  - export GEM_HOME=$HOME/.gem
  - export GEM_PATH=$HOME/.gem
  - rvm get stable --auto-dotfiles
  - rvm install 2.3.1
  - gem install --no-ri --no-rdoc fpm
  - fpm --version
  - fpm --help
  - export PATH=$(ruby -r rubygems -e 'puts Gem.dir'):$PATH
#  - fpm -s dir -t deb -C src --name digitalbits-core --version 0.1.0 --iteration 1 --depends debian_dependency1 --description "Digitalbits-core" .
#  - fpm -s dir -t rpm -C src --name digitalbits-core --version 0.1.0 --iteration 1 --depends  redhat_dependency1 --description "digitalbits-core" .
  
before_deploy: 
  - export PATH=$(ruby -r rubygems -e 'puts Gem.dir'):$PATH
  - pyenv global 2.7
  - pip install cloudsmith-cli
  - gem install --no-ri --no-rdoc fpm
  - fpm --version

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh 2>&1
  on:
    branch: OS-16
